# Generated by Django 5.2.1 on 2026-04-25 16:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemoignageMasterclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=60)),
                ('texte', models.TextField(blank=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage Masterclass',
                'verbose_name_plural': 'Témoignages Masterclass',
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
