# Generated by Django 4.2.30 on 2026-05-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0002_temoignagemasterclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='slug',
            field=models.SlugField(blank=True, help_text='ex: ose-etre-toi, art-oratoire', unique=True),
        ),
    ]
