# Generated by Django 6.0.3 on 2026-03-31 13:29

import cadeaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartesCadeaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=cadeaux.models.gen_code, max_length=20, unique=True)),
                ('formule', models.CharField(choices=[('F1', 'Live · Groupe'), ('F2', 'Live · Privé'), ('F3', 'Présentiel · Groupe'), ('F4', 'Présentiel · Privé')], max_length=4)),
                ('acheteur_nom', models.CharField(max_length=100)),
                ('acheteur_email', models.EmailField(max_length=254)),
                ('acheteur_tel', models.CharField(blank=True, max_length=20)),
                ('destinataire_nom', models.CharField(max_length=100)),
                ('destinataire_email', models.EmailField(blank=True, max_length=254)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('message_perso', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('utilisee', 'Utilisée'), ('expiree', 'Expirée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('utilisee_par', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
