# Generated by Django 4.2.30 on 2026-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=30)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('type_rdv', models.CharField(choices=[('decouverte', 'Appel Découverte'), ('coaching', 'Séance de Coaching'), ('consultation', 'Consultation Image & Style')], max_length=20)),
                ('mode', models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'En présentiel')], max_length=20)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('paiement_recu', models.BooleanField(default=False)),
                ('note_admin', models.TextField(blank=True)),
                ('lien_reunion', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'ordering': ['-date', '-heure'],
                'unique_together': {('date', 'heure')},
            },
        ),
    ]
