# Generated by Django 4.2.30 on 2026-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rendezvous',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='nb_seances',
            field=models.CharField(blank=True, choices=[('1', '1 séance'), ('2', '2 séances'), ('3+', '3 séances ou plus')], default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='prix',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='type_rdv',
            field=models.CharField(choices=[('appel_decouverte', 'Appel Découverte'), ('bilan_image', 'Bilan Image'), ('seance_coaching', 'Séance de Coaching')], max_length=30),
        ),
    ]
