# Generated by Django 4.2.28 on 2026-04-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('prenom', models.CharField(blank=True, max_length=60)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
