# Generated by Django 5.2.1 on 2026-04-09 15:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0002_add_abonne_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
