# Generated by Django 4.2.28 on 2026-04-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0003_alter_guide_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='code_acces',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
