# Generated by Django 5.2.1 on 2026-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0004_replay_code_acces'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationBrunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=60)),
                ('nom', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=30)),
                ('type_pass', models.CharField(choices=[('metamorphosee', 'Pass Métamorphosée — 50 000 FCFA'), ('decouverte', 'Pass Découverte — 30 000 FCFA'), ('vip', 'Pass VIP — 60 000 FCFA')], max_length=20)),
                ('montant', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Paiement déclaré'), ('confirme', 'Confirmé par Prélia'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('token_succes', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Réservation Brunch',
                'verbose_name_plural': 'Réservations Brunch',
                'ordering': ['-created_at'],
            },
        ),
    ]
