# Generated by Django 5.2.1 on 2026-04-15 05:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('resume', models.TextField()),
                ('bouton', models.CharField(blank=True, max_length=100)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('color', models.CharField(default='#C9A96A', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('badge_color', models.CharField(default='#C9A96A', max_length=20)),
                ('date', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('bouton', models.CharField(blank=True, max_length=100)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_venir', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
