# Generated by Django 5.2.1 on 2026-04-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='evenement',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
