# Generated by Django 6.0.3 on 2026-04-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='audio_fichier',
            field=models.FileField(blank=True, null=True, upload_to='temoignages/audios/'),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='type_temo',
            field=models.CharField(choices=[('texte', 'Texte'), ('video', 'Vidéo'), ('audio', 'Audio')], default='texte', max_length=10),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='video_fichier',
            field=models.FileField(blank=True, null=True, upload_to='temoignages/videos/'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='texte',
            field=models.TextField(blank=True),
        ),
    ]
