# Generated by Django 5.2.1 on 2026-04-09 15:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_temoignage_audio_fichier_temoignage_type_temo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignage',
            name='audio_fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='photo_apres',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='photo_avant',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='video_fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
