# Generated by Django 5.2.1 on 2026-04-27 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReunionZoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('join_url', models.URLField(blank=True)),
                ('start_url', models.URLField(blank=True, max_length=1000)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('active', 'Active'), ('terminee', 'Terminée')], default='attente', max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('duree', models.IntegerField(default=60, help_text='Durée en minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions_zoom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
