# Generated by Django 4.2.28 on 2026-04-08 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('formule', models.CharField(blank=True, max_length=4)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('checkout', 'Initié par le membre'), ('webhook', 'Confirmé par webhook'), ('manual', 'Activation manuelle admin')], default='checkout', max_length=20)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
