# Generated by Django 5.2.1 on 2026-04-15 05:48

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(db_index=True, max_length=32, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('premiere_connexion', models.BooleanField(default=True)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('utilisee_le', models.DateTimeField(blank=True, null=True)),
                ('utilisatrice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cle_communaute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Clé d'accès communauté",
            },
        ),
        migrations.CreateModel(
            name='ProfilCommunaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.TextField(blank=True)),
                ('secteur', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('situation_mat', models.CharField(blank=True, max_length=100)),
                ('passion', models.TextField(blank=True)),
                ('apport_metamorphose', models.TextField(blank=True)),
                ('attentes', models.TextField(blank=True)),
                ('onboarding_fait', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisatrice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_communaute', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('type_media', models.CharField(choices=[('texte', 'Texte'), ('photo', 'Photo'), ('video', 'Vidéo')], default='texte', max_length=10)),
                ('media', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media')),
                ('pour_coach', models.BooleanField(default=False)),
                ('epingle', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-epingle', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('est_coach', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='communaute.publication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
