# Generated by Django 4.2.30 on 2026-05-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communaute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleAccesEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('cle', models.CharField(max_length=32, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clé accès email externe',
            },
        ),
    ]
