# Generated by Django 5.2.1 on 2026-04-13 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('active', 'Active'), ('terminee', 'Terminée')], default='attente', max_length=20)),
                ('max_participants', models.IntegerField(default=1000)),
                ('mode', models.CharField(choices=[('reunion', 'Réunion'), ('webinaire', 'Webinaire'), ('live', 'Live')], default='reunion', max_length=20)),
                ('enregistrement_actif', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('hote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles_hote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('hote', 'Hôte'), ('coanimateur', 'Co-animateur'), ('participant', 'Participant'), ('spectateur', 'Spectateur')], default='participant', max_length=20)),
                ('rejoint_at', models.DateTimeField(auto_now_add=True)),
                ('quitte_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live.salle')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
