# Generated by Django 4.2.28 on 2026-04-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_peeractif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='salle',
            name='code_acces',
            field=models.CharField(blank=True, help_text='Code généré automatiquement à la création', max_length=10),
        ),
    ]
