# Generated by Django 5.2.1 on 2026-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_remove_salle_mot_de_passe_salle_code_acces'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='daily_room_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
