# Generated by Django 5.2.1 on 2026-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_salle_daily_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='lien_zoom',
            field=models.URLField(blank=True, help_text='Lien de réunion Zoom'),
        ),
    ]
