# Generated by Django 4.2.28 on 2026-04-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='✦', max_length=10)),
                ('couleur', models.CharField(default='#C9A96A', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('semaine', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(choices=[('texte', 'Article'), ('video', 'Vidéo'), ('audio', 'Audio'), ('pdf', 'PDF')], default='texte', max_length=10)),
                ('contenu', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('duree', models.CharField(blank=True, max_length=20)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('actif', models.BooleanField(default=True)),
                ('en_vedette', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='learning.categorie')),
            ],
            options={
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
