# Generated by Django 5.2.1 on 2026-04-15 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_create_learning_models'),
        ('paiement', '0001_add_transaction_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manuel', 'Activation manuelle — Coach Prélia APEDO AHONON'), ('webhook', 'Confirmation automatique — Webhook'), ('offert', 'Offert par Coach Prélia APEDO  AHONON')], default='manuel', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='learning.cours')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces_cours', to='paiement.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_cours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acces Cours',
                'verbose_name_plural': 'Acces Cours',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'cours')},
            },
        ),
    ]
