# Generated by Django 5.2.1 on 2026-04-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_accescours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='lien_achat',
            field=models.URLField(blank=True, help_text='Lien de paiement externe fourni par Coach Prélia APEDO AHONON'),
        ),
        migrations.AddField(
            model_name='cours',
            name='prix',
            field=models.PositiveIntegerField(default=0, help_text='Prix en FCFA — 0 = gratuit'),
        ),
    ]
