# Generated by Django 5.2.1 on 2026-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email de la Métamorphosée')),
                ('cle', models.CharField(max_length=12, unique=True, verbose_name="Clé d'accès")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': "Clé d'accès Communauté",
                'verbose_name_plural': "Clés d'accès Communauté",
                'ordering': ['-created_at'],
            },
        ),
    ]
