# Generated by Django 4.2.30 on 2026-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_create_tickets_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='montant_paye',
            field=models.PositiveIntegerField(default=0, help_text='Montant payé en FCFA'),
        ),
    ]
