# Generated by Django 5.2.1 on 2026-04-17 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('active', 'En cours'), ('terminee', 'Terminée')], default='planifiee', max_length=20)),
                ('places_max', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vague',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('non_lu_admin', models.IntegerField(default=0)),
                ('non_lu_membre', models.IntegerField(default=0)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FormulaireSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('complete_le', models.DateTimeField(blank=True, null=True)),
                ('note_globale', models.IntegerField(blank=True, null=True)),
                ('note_coach', models.IntegerField(blank=True, null=True)),
                ('note_contenu', models.IntegerField(blank=True, null=True)),
                ('note_transformation', models.IntegerField(blank=True, null=True)),
                ('point_fort', models.TextField(blank=True)),
                ('point_ameliorer', models.TextField(blank=True)),
                ('recommanderait', models.BooleanField(blank=True, null=True)),
                ('commentaire_libre', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulaire satisfaction',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('est_admin', models.BooleanField(default=False)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inscription', 'Nouvelle inscription'), ('temoignage', 'Nouveau témoignage'), ('contact', 'Nouveau message'), ('paiement', 'Paiement reçu'), ('ticket', 'Nouveau ticket'), ('satisfaction', 'Formulaire satisfaction'), ('message', 'Message membre'), ('system', 'Système')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_generees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_actuelle', models.PositiveIntegerField(default=1)),
                ('sessions_completees', models.PositiveIntegerField(default=0)),
                ('sessions_total', models.PositiveIntegerField(default=16)),
                ('notes_coach', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression',
            },
        ),
        migrations.CreateModel(
            name='SessionAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_session', models.CharField(choices=[('live_groupe', 'Live Groupe'), ('live_prive', 'Live Privé'), ('masterclass', 'Masterclass'), ('reunion', 'Réunion interne'), ('autre', 'Autre')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('lien_live', models.URLField(blank=True)),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membres_invites', models.ManyToManyField(blank=True, related_name='sessions_invitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session agenda',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MembreVague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagues', to=settings.AUTH_USER_MODEL)),
                ('vague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='notifications.vague')),
            ],
            options={
                'unique_together': {('vague', 'membre')},
            },
        ),
    ]
